# ansible_path/group_vars/f2b.yaml

# Docker service Fail2ban
dockerServiceFail2banContainerName: 'fail2ban-{{ inventory_hostname }}'
dockerServiceFail2banImage: 'crazymax/fail2ban:1.0.1'
dockerServiceFail2banDestNotifEmail: '{{ vaultDockerServiceFail2banDestNotifEmail }}'
dockerServiceFail2banCapabilities: ['NET_ADMIN', 'NET_RAW']
dockerServiceFail2banPrivileged: true
dockerServiceFail2banNetworkMode: host
dockerServiceFail2banVolumes:
  ['/srv/fail2ban/data:/data', '/srv/logs:/srv/logs:ro', '/var/log:/var/log:ro']
dockerServiceFail2banEnvVars:
  {
    TZ: 'Europe/Paris',
    F2B_LOG_TARGET: 'STDOUT',
    F2B_LOG_LEVEL: 'INFO',
    F2B_ACTION: '%(action_mw)s',
    F2B_DEST_EMAIL: '{{ vaultDockerServiceFail2banDestNotifEmail }}',
    SSMTP_HOST: 'mail.infomaniak.com',
    SSMTP_PORT: '587',
    SSMTP_USER: '{{ eximAccountEmail }}',
    SSMTP_PASSWORD: '{{ eximAccountPassword }}',
    SSMTP_HOSTNAME: '{{ serverHostname }}',
    SSMTP_TLS: 'NO',
    SSMTP_STARTTLS: 'YES',
    F2B_IPTABLES_CHAIN: 'INPUT'
  }
