# ansible_path/group_vars/portainer.yaml

dockerServiceStandaloneNetwork: 'reverse-proxy-nw'

# Docker service Portainer
dockerServicePortainerContainerName: 'portainer-agent-{{ inventory_hostname }}'
dockerServicePortainerImage: 'portainer/agent:2.16.2-alpine'
dockerServicePortainerPorts: '9001:9001'
dockerServicePortainerVolumes:
  ['/var/run/docker.sock:/var/run/docker.sock', '/var/lib/docker/volumes:/var/lib/docker/volumes']

# Docker service Nginx Proxy Manager
dockerServiceProxyContainerName: 'nginx-proxy-manager-{{ inventory_hostname }}'
dockerServiceProxyImage: 'jc21/nginx-proxy-manager:2.9.18'
dockerServiceProxyPorts: ['80:80', '443:443', '81:81']
dockerServiceProxyEnvVars: { TZ: 'Europe/Paris' }
dockerServiceProxyNetworks: [{ name: '{{ dockerServiceStandaloneNetwork }}' }]
dockerServiceProxyVolumes:
  [
    '/srv/nginx-proxy-manager/data:/data',
    '/srv/logs/nginx-proxy-manager:/data/logs/',
    '/srv/nginx-proxy-manager/data/letsencrypt:/etc/letsencrypt'
  ]

# Docker service Main Site
dockerServiceMainSiteContainerName: 'main-site-{{ inventory_hostname }}'
dockerServiceMainSiteImage: 'lgdweb/nginx-test:latest'
dockerServiceMainSiteNetworks: [{ name: '{{ dockerServiceStandaloneNetwork }}' }]
dockerServiceMainSiteVolumes:
  [
    '/srv/logs/nginx:/var/log/nginx',
    '/etc/localtime:/etc/localtime:ro',
    '/etc/timezone:/etc/timezone:ro'
  ]
