# ansible_path/host_vars/vm1/vm1.yaml

rootUserPassword: "{{ vaultRootUserPassword | password_hash('sha512') }}"

sshAdminUserName: "{{ vaultSshAdminUserName }}"
sshAdminUserGroup: "{{ vaultSshAdminUserGroup }}"
sshAdminUserPassword: "{{ vaultSshAdminUserPassword | password_hash('sha512') }}"
sshAdminUserCreateHome: true
sshAdminUserShell: /bin/bash

eximAccountEmail: "{{ vaultEximAccountEmail }}"
eximAccountPassword: "{{ vaultEximAccountPassword }}"

mongodbAdminUsername: "{{ vaultMongodbAdminUsername }}"
mongodbAdminPassword: "{{ vaultMongodbAdminPassword }}"
