# ansible_path/roles/apt/keys/tasks/main.yaml
---
- name: APT KEYS | Create directory for GPG keys
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: '0755'
  become: true
  tags: [apt, key]

- name: APT KEYS | Download and save GPG key
  ansible.builtin.get_url:
    url: '{{ aptKeyUri }}'
    dest: '/etc/apt/keyrings/{{ aptRepoName }}.asc'
    mode: '0644'
  become: true
  tags: [apt, key]

- name: APT KEYS | Set permissions for GPG key
  ansible.builtin.file:
    path: '/etc/apt/keyrings/{{ aptRepoName }}.asc'
    mode: '0644'
  become: true
  tags: [apt, key]
