# ansible_path/rollbacks/dockerServices/nginx-proxy/tasks/main.yaml

---

- name: ROLLBACK DOCKER SERVICES NGINX PROXY | Stop the nginx-proxy container
  community.docker.docker_container:
    name: "{{ nginxProxyContainerName }}"
    state: absent
    container_default_behavior: compatibility
    purge_networks: yes
  tags: [rollback, dockerServices, stopContainer, nginxProxy]

- name: ROLLBACK DOCKER SERVICES NGINX PROXY | Remove nginx-proxy image
  community.docker.docker_image:
    name: "{{ nginxProxyImage }}"
    state: absent
    rm: yes
    force: yes
  tags: [rollback, dockerServices, removeImage, nginxProxy]
