# ansible_path/projects/taskManager/deploy.yaml

---

- hosts: lisa
  vars:
    createUserDatabase: yes
    appDbUsername: "{{ vaultTaskManagerDbUsername }}"
    appDbPassword: "{{ vaultTaskManagerDbPassword }}"
    appDbName: "{{ vaultTaskManagerDbName }}"
    taskManagerContainerName: taskManager
    taskManagerImageName: tuximetal/task-manager
    taskManagerImageVersion: 0.0.2
    taskManagerLinks: [ "mongodb:mongo" ]
    taskManagerEnvVars: "{{ vaultTaskManagerEnvVars }}"
    taskManagerVolumes: [
      "/etc/localtime:/etc/localtime:ro",
      "/etc/timezone:/etc/timezone:ro"
    ]
  vars_files:
    - ../../vault/taskManager/vault.yaml
  roles:
    # Create the mongo user and database for taskManager project
    - ../../roles/dockerServices/mongo

    # Pull app image from docker hub
    - {
      role: ../../roles/docker/image,
        projectAppImageName: "{{ taskManagerImageName }}:{{ taskManagerImageVersion }}"
    }

    # Run taskManager container image
    - {
      role: ../../roles/docker/container,
        projectAppContainerName: "{{ taskManagerContainerName }}",
        projectAppImageName: "{{ taskManagerImageName }}:{{ taskManagerImageVersion }}",
        projectAppLinks: "{{ taskManagerLinks }}",
        projectAppEnvVars: "{{ taskManagerEnvVars }}",
        projectAppVolumes: "{{ taskManagerVolumes }}"
    }
