# ansible_path/rollbacks/docker/image/tasks/main.yaml
---
- name: ROLLBACK DOCKER IMAGE PULL | Remove docker image {{ projectAppImageName }}
  community.docker.docker_image:
    name: '{{ projectAppImageName }}'
    state: absent
    force_absent: true
  tags: [rollback, docker, removeImage]
