# ansible_path/rollbacks/docker/image/tasks/main.yaml

---

- name: ROLLBACK DOCKER IMAGE PULL | Remove {{ projectAppImageName }} image
  community.docker.docker_image:
    name: "{{ projectAppImageName }}"
    state: absent
    force_absent: yes
  tags: [rollback, docker, removeImage]
