all:
  hosts:
    alice:
      ansible_ssh_host: 193.70.113.138 # alice.lgdweb.ovh
      ansible_user: debian
    almanzo:
      ansible_ssh_host: 193.70.113.102 # almanzo.lgdweb.ovh
      ansible_user: debian
    andrew:
      ansible_ssh_host: 89.233.108.164 # andrew.lgdweb.ovh
      ansible_user: root
    laura:
      ansible_ssh_host: 37.187.180.215 # laura.lgdweb.ovh
      ansible_user: debian
    mary:
      ansible_ssh_host: 151.80.155.178 # mary.lgdweb.ovh
      ansible_user: debian
    nelson:
      ansible_ssh_host: 51.83.97.35 # nelson.lgdweb.ovh
      ansible_user: debian
  children:
    docker:
      hosts:
        alice:
        almanzo:
        andrew:
        laura:
        mary:
        nelson:
    f2b:
      hosts:
        alice:
        almanzo:
        andrew:
        laura:
        mary:
        nelson:
    standalone:
      hosts:
        andrew:
        laura:
        mary:
