# ansible_path/roles/exim/sendmail/tasks/main.yaml

---

- name: EXIM SEND EMAIL | Sending notification to {{ eximDestEmail }}
  mail:
    to: "{{ eximDestEmail }}"
    subject: "{{ eximEmailSubject }}"
    body: "{{ eximEmailBody }}"
    from: "{{ eximAccountEmail }}"
  tags: [exim, sendemail]
