# ansible_path/rollbacks/apt/keys/tasks/main.yaml

---

- name: ROLLBACK APT KEYS | Remove a GPG key
  apt_key:
    url: "{{ aptKeyUri }}"
    id: "{{ aptKeyId }}"
    state: absent
  tags: [rollback, apt, key]
