# ansible_path/roles/docker/image/tasks/main.yaml

---

- name: DOCKER IMAGE PULL | Pull {{ projectAppImageName }} image
  community.docker.docker_image:
    name: "{{ projectAppImageName }}"
    source: pull
  tags: [docker, pullImage]
