# ansible_path/roles/docker/image/tasks/main.yaml
---
- name: 'DOCKER IMAGE PULL | Pull image {{ projectAppImageName }}'
  community.docker.docker_image:
    name: '{{ projectAppImageName }}'
    source: pull
    force_source: '{{ forcePull | default(false) }}'
  tags: [docker, pullImage]
