# ansible_path/rollbacks/users/removeUserFromGroups/tasks/main.yaml
---
- name: REMOVE USER FROM GROUPS | Check if user is already removed from groups
  ansible.builtin.getent:
    database: group
    key: '{{ item }}'
  loop: '{{ userGroups }}'
  register: groupInfo
  failed_when: false
  tags: [rollback, users, remove-user-from-groups, check-group]

- name: Gather the facts again
  ansible.builtin.setup:
  tags: [rollback, users, remove-user-from-groups, gether-facts]

- name: REMOVE USER FROM GROUPS | Remove user from groups {{ userGroups }}
  ansible.builtin.command:
    cmd: 'gpasswd -d {{ userName }} {{ item }}'
  loop: '{{ userGroups }}'
  when:
    - userGroups is defined
    - ansible_facts['groups'][item] is defined
  changed_when: groupInfo is defined and groupInfo is not failed
  tags: [rollback, users, remove-user-from-groups]
