# ansible_path/rollbacks/users/removeUserFromGroups/tasks/main.yaml
---
- name: REMOVE USER FROM GROUPS | Remove the user {{ userName }} from the groups {{ userGroups }}
  command: 'gpasswd -d {{ userName }} {{ item }}'
  ignore_errors: true
  with_items: '{{ userGroups }}'
  tags: [rollback, users, remove-user-from-groups]
