# ansible_path/playbooks/webserver/mainServices.yaml
---
- name: MAIN SERVICES | Main services for webserver
  hosts: docker:&f2b
  gather_facts: false
  vars:
    webPorts: [{ port: 'http', proto: 'tcp' }, { port: 'https', proto: 'tcp' }]
    eximDestEmail: me@lgdweb.fr
    eximEmailSubject: 'Ansible webserver task done on server'
    eximEmailBody: 'All mainServices tasks are done successfully'
  roles:
    # Create data structure for services
    - roles/dockerServices/dataStructure

    # Pull Fail2ban image
    - { role: roles/docker/image, projectAppImageName: '{{ dockerServiceFail2banImage }}' }

    # Start Fail2ban docker container
    - {
        role: roles/docker/container,
        projectAppContainerName: '{{ dockerServiceFail2banContainerName }}',
        projectAppImageName: '{{ dockerServiceFail2banImage }}',
        projectAppCapAdd: '{{ dockerServiceFail2banCapabilities }}',
        projectAppNetworkMode: '{{ dockerServiceFail2banNetworkMode }}',
        projectAppPrivileged: '{{ dockerServiceFail2banPrivileged }}',
        projectAppVolumes: '{{ dockerServiceFail2banVolumes }}',
        projectAppEnvVars: '{{ dockerServiceFail2banEnvVars }}'
      }

    # Allow http and https ports in firewall
    - { role: roles/firewall/allow, firewallPorts: '{{ webPorts }}' }

    # Sending Notification email
    - roles/exim/sendemail
