# ansible_path/playbooks/webserver/rollback.yaml
---
- hosts: docker:&f2b
  gather_facts: false
  roles:
    # Stop fail2ban docker container
    - {
        role: ../../rollbacks/docker/container,
        projectAppContainerName: '{{ dockerServiceFail2banContainerName }}'
      }

    # Clean fail2ban docker image
    - {
        role: ../../rollbacks/docker/image,
        projectAppImageName: '{{ dockerServiceFail2banImage }}'
      }

    # Remove docker service data structure
    - ../../rollbacks/dockerServices/dataStructure
