# ansible_path/roles/system/hostname/tasks/main.yaml
---
- name: SYSTEM HOSTNAME | Set the hostname
  ansible.builtin.hostname:
    name: '{{ serverHostname }}'
  register: changeHostname
  tags: [system, hostname]
