# ansible_path/roles/apt/install/tasks/main.yaml

---

- name: APT INSTALL | Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ aptPackages }}"
  tags: [apt, apt-install]
