# ansible_path/playbooks/docker/install.yaml
---
- hosts: docker
  become: yes
  vars:
    eximDestEmail: me@lgdweb.fr
    eximEmailSubject: 'Ansible docker install task done on server'
    eximEmailBody: 'All docker install tasks are done successfully'
  roles:
    # Add Docker apt repository
    - {
        role: ../../roles/apt/repository,
        aptRepoUrl: '{{ dockerAptRepoUri }}',
        aptRepoName: '{{ dockerAptRepoName }}'
      }

    # Add docker Gpg key
    - {
        role: ../../roles/apt/keys,
        aptKeyUri: '{{ dockerAptKeyUri }}',
        aptKeyId: '{{ dockerAptKeyId }}'
      }

    # Install Docker package
    - { role: ../../roles/apt/install, aptPackages: '{{ dockerPackages }}' }

    # Add admin user to Docker group
    - {
        role: ../../roles/users/addUserToGroups,
        userName: '{{ sshAdminUserName }}',
        userGroups: docker
      }

    # Sending Notification email
    - ../../roles/exim/sendemail
