# ansible_path/roles/dockerServices/dataStructure/tasks/main.yaml
---
- name: DOCKER SERVICE DATA STRUCTURE | Create {{ mainDataDirectory }} directory
  become: yes
  file:
    path: '{{ mainDataDirectory }}'
    state: directory
    owner: 1000
    group: 1000
  tags: [dockerService, dataStructure]

- name: DOCKER SERVICE DATA STRUCTURE | Get data directory structure from Github
  git:
    dest: '{{ mainDataDirectory }}'
    force: yes
    repo: '{{ dataStructureRepo }}'
    update: yes
  tags: [dockerServices, dataStructure, git]
