# ansible_path/rollbacks/users/user/tasks/main.yaml
---
- name: ROLLBACK USER | Remove the user {{ userName }}
  ansible.builtin.user:
    name: '{{ userName }}'
    groups: null
    force: true
    state: absent
    remove: true
  # register: removedUser
  # changed_when: removedUser.changed
  tags: [rollback, user, remove-user]
# - name: ROLLBACK USER | Find and remove all files/directories with nogroup/nouser
#   ansible.builtin.shell:
#     cmd: 'set -o pipefail && find /home -nouser -nogroup -type d -print0 | xargs -0 -r rm -rf'
#   changed_when: removedUser.changed
#   failed_when: false
#   tags: [rollback, user, remove-user]
