# ansible_path/roles/docker/network/tasks/main.yaml
---
- name: DOCKER NETWORK CREATE | Create {{ projectAppNetworkName }} network
  community.docker.docker_network:
    name: '{{ projectAppNetworkName }}'
    attachable: yes
    state: present
  tags: [docker, networkCreate]
