# ansible_path/roles/docker/network/tasks/main.yaml
---
- name: DOCKER NETWORK CREATE | Create docker network {{ projectAppNetworkName }}
  community.docker.docker_network:
    name: '{{ projectAppNetworkName }}'
    attachable: true
    state: present
  tags: [docker, networkCreate]
