# ansible_path/roles/system/sshConfig/tasks/main.yaml
---
- name: SYSTEM SSHCONFIG | Check if there is a backup file for default ssh config
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config.backup
  register: fileExists
  tags: [system, ssh, ssh-config, backup-config, file-exists]

- name: SYSTEM SSHCONFIG | Copy the default ssh config in a backup file
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    mode: '0644'
    remote_src: true
  register: isCopyed
  when: not fileExists.stat.exists
  tags: [system, ssh, ssh-config, backup-config, copy-config-file]

- name: SYSTEM SSHCONFIG | Apply sshd config template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/ansible.conf
    owner: root
    group: root
    mode: '0644'
  notify: RestartSsh
  tags: [system, ssh, ssh-config]

- name: SYSTEM SSHCONFIG | Add user authorized_keys file
  ansible.posix.authorized_key:
    user: '{{ sshAdminUserName }}'
    state: present
    key: '{{ item }}'
  with_items: '{{ sshAuthorizedKeys }}'
  tags: [system, ssh, ssh-config, ssh-authorizedKeys]
