# ansible_path/roles/system/sshConfig/tasks/main.yaml

---

- name: SYSTEM SSHCONFIG | Check if there is a backup file for default ssh config
  stat:
    path: /etc/ssh/sshd_config.backup
  register: fileExists
  tags: [system, ssh, ssh-config, backup-config, file-exists]

- name: SYSTEM SSHCONFIG | Copy the default ssh config in a backup file
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    remote_src: yes
  register: isCopyed
  when: fileExists.stat.exists == False
  tags: [system, ssh, ssh-config, backup-config, copy-config-file]

- name: SYSTEM SSHCONFIG | Edit ssh config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items: "{{ sshConfig }}"
  when: isCopyed is success or isCopyed is skipped
  tags: [system, ssh, ssh-config]
  notify: restartSsh

- name: SYSTEM SSHCONFIG | Add "{{ sshAdminUserName }}" authorized_keys file
  authorized_key:
    user: "{{ sshAdminUserName }}"
    state: present
    key: '{{ item }}'
  with_items: "{{ sshAuthorizedKeys }}"
  tags: [system, ssh, ssh-config, ssh-authorizedKeys]
