# ansible_path/roles/dockerServices/nginx-proxy/tasks/main.yaml
---
- name: DOCKER SERVICES NGINX PROXY | Pull nginx-proxy image
  community.docker.docker_image:
    name: '{{ nginxProxyImage }}'
    source: pull
  tags: [dockerServices, pullImage, nginxProxy]

- name: DOCKER SERVICES NGINX PROXY | Run the nginx-proxy container
  community.docker.docker_container:
    name: nginx-proxy
    image: '{{ nginxProxyImage }}'
    state: started
    restart_policy: always
    networks:
      - name: '{{ nginxProxyNetworkName }}'
    ports:
      - '80:80'
      - '443:443'
    volumes: '{{ nginxProxyVolumes }}'
  tags: [dockerServices, runContainer, nginxProxy]
