# ansible_path/roles/dockerServices/mongo/defaults/main.yaml

mongoImage: mongo:4.0.4
mongoVolumes: [
  "/data/mongo:/data/db",
  "/etc/localtime:/etc/localtime:ro",
  "/etc/timezone:/etc/timezone:ro"
]
mongoEnvVars: {
  MONGO_INITDB_ROOT_USERNAME: "{{ mongodbAdminUsername }}",
  MONGO_INITDB_ROOT_PASSWORD: "{{ mongodbAdminPassword }}"
}
