# ansible_path/rollbacks/docker/container/tasks/main.yaml
---
- name: ROLLBACK DOCKER CONTAINER | Stop docker container {{ projectAppContainerName }}
  community.docker.docker_container:
    name: '{{ projectAppContainerName }}'
    state: absent
    container_default_behavior: compatibility
    networks: []
  tags: [rollback, docker, stopContainer]
