# ansible_path/roles/users/admin/tasks/main.yaml

---

- name: USER ADMIN | Copy .bashrc file in user {{ userName }} home dir
  get_url:
    url: "{{ bashrcUri }}"
    dest: "{{ userHome }}/.bashrc"
    group: "{{ userGroup }}"
    owner: "{{ userName }}"
    backup: yes
  when: userIsAdmin
  tags: [users, user-admin, bashrc-file]

- name: USER ADMIN | Set {{ userName }} in sudoers file
  copy:
    content: "{{ userName }} ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/{{ userName }}
    group: root
    owner: root
    mode: 0440
  when: userIsAdmin and userName != "root"
  tags: [users, user-admin, sudoers-file]
