# ansible_path/host_vars/laura/laura.yaml

rootUserPassword: "{{ vaultRootUserPassword | password_hash('sha512') }}"

sshAdminUserName: '{{ vaultSshAdminUserName }}'
sshAdminUserGroup: '{{ vaultSshAdminUserGroup }}'
sshAdminUserPassword: "{{ vaultSshAdminUserPassword | password_hash('sha512') }}"
sshAdminUserCreateHome: true
sshAdminUserShell: /bin/bash

eximAccountEmail: '{{ vaultEximAccountEmail }}'
eximAccountPassword: '{{ vaultEximAccountPassword }}'

mongodbAdminUsername: '{{ vaultMongodbAdminUsername }}'
mongodbAdminPassword: '{{ vaultMongodbAdminPassword }}'
