# ansible_path/roles/firewall/allow/tasks/main.yaml
---
- name: FIREWALL ALLOW RULE | Allow all access to tcp ports {{ firewallPorts }}
  become: true
  ufw:
    state: enabled
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  with_items: '{{ firewallPorts }}'
  tags: [firewall, ufw-alow]
