# ansible_path/roles/dockerServices/letsencrypt/tasks/main.yaml
---
- name: DOCKER SERVICES LETSENCRYPT | Pull letsencrypt-companion image
  community.docker.docker_image:
    name: '{{ letsencryptImage }}'
    source: pull
  tags: [dockerServices, pullImage, letsencrypt]

- name: DOCKER SERVICES LETSENCRYPT | Run the letsencrypt-companion container
  community.docker.docker_container:
    name: nginx-letsencrypt
    image: '{{ letsencryptImage }}'
    state: started
    container_default_behavior: compatibility
    restart_policy: always
    networks:
      - name: '{{ nginxProxyNetworkName }}'
    env: '{{ letsencryptEnvVars }}'
    volumes_from: '{{ nginxProxyContainer }}'
    volumes: '{{ letsencryptVolumes }}'
  tags: [dockerServices, runContainer, letsencrypt]
