# ansible_path/roles/docker/container/tasks/main.yaml
---
- name: DOCKER CONTAINER RUN | Run {{ projectAppContainerName }} container
  community.docker.docker_container:
    name: '{{ projectAppContainerName }}'
    image: '{{ projectAppImageName }}'
    state: started
    container_default_behavior: '{{ projectAppCompatibility }}'
    network_mode: '{{ projectAppNetworkMode }}'
    restart_policy: '{{ projectAppRestartPolicy }}'
    privileged: '{{ projectAppPrivileged }}'
    capabilities: '{{ projectAppCapAdd }}'
    volumes: '{{ projectAppVolumes }}'
    links: '{{ projectAppLinks }}'
    ports: '{{ projectAppPorts }}'
    env: '{{ projectAppEnvVars }}'
    networks: '{{ projectAppNetworks }}'
  tags: [docker, runContainer]
