# ansible_path/roles/docker/container/tasks/main.yaml

---

- name: DOCKER CONTAINER RUN | Run {{ projectAppContainerName }} container
  docker_container:
    name: "{{ projectAppContainerName }}"
    image: "{{ projectAppImageName }}"
    state: started
    volumes: "{{ projectAppVolumes }}"
    links: "{{ projectAppLinks }}"
    env: "{{ projectAppEnvVars }}"
  tags: [docker, runContainer]
