# ansible_path/rollbacks/docker/network/tasks/main.yaml
---
- name: DOCKER NETWORK ROLLBACK | Delete docker network and disconnect all containers
  community.docker.docker_network:
    name: '{{ projectAppNetworkName }}'
    state: absent
    force: true
  tags: [docker, networkDelete]
