# ansible_path/playbooks/init/clean-reset.yaml
---
- name: INIT | Clean reset
  hosts: all
  vars:
    userIsAdmin: true
    userName: '{{ sshAdminUserName }}'
    userGroup: '{{ sshAdminUserGroup }}'
    userHome: '/home/{{ sshAdminUserName }}'
  roles:
    # 1: Remove ssh admin user configuration
    - rollbacks/users/admin

    # 2: Remove ssh admin user
    - rollbacks/users/user

    # 3: Remove ssh admin user group
    - rollbacks/users/group
