# ansible_path/playbooks/init/init.yaml
---
- name: INITIAL SERVER SETUP | Init server
  hosts: all
  become: true
  vars:
    userSsh: true
    userShell: /bin/bash
    userIsAdmin: true
    aptPackages: '{{ systemAptPackages + defaultAptPackages + utilsAptPackages }}'
    eximDestEmail: me@lgdweb.fr
    eximEmailSubject: 'Ansible init task done on server'
    eximEmailBody: 'All init tasks are done successfully'
  roles:
    # 1: Add default apt repository
    - roles/apt/repository

    # 2: Install default and utils packages
    - roles/apt/install

    # 3: Firewall init configuration
    - roles/firewall/init
    # 3.1: Allow defaults ports in firewall
    - roles/firewall/allow

    # 4: Root user configuration
    - roles/users/admin

    # 5: Timezone configuration
    - roles/system/timezone

    # 6: Hostname configuration
    - roles/system/hostname

    # 7: Logrotate configuration
    - roles/system/logrotate

    # 8: Open ntp configuration
    - roles/system/openNtp

    # 9: Locales configuration
    - roles/system/locales

    # 10: Add default admin user group
    - { role: roles/users/group, userGroup: '{{ sshAdminUserGroup }}' }

    # 11: Add default admin user
    - {
        role: roles/users/user,
        userName: '{{ sshAdminUserName }}',
        userGroup: '{{ sshAdminUserGroup }}',
        userHome: '/home/{{ sshAdminUserName }}',
        userCreateHome: '{{ sshAdminUserCreateHome }}',
        userPassword: '{{ sshAdminUserPassword }}'
      }

    # 12: Add default admin user configuration
    - {
        role: roles/users/admin,
        userName: '{{ sshAdminUserName }}',
        userGroup: '{{ sshAdminUserGroup }}',
        userHome: '/home/{{ sshAdminUserName }}'
      }

    # 13: Exim configuration
    - roles/exim/config

    # 14: Ssh configuration
    - roles/system/sshConfig

    # 15: Sending Notification email
    - roles/exim/sendemail
