# ansible_path/rollbacks/apt/repository/tasks/main.yaml
---
- name: ROLLBACK APT REPOSITORY | Check if there is a backup file for default sources.list file
  stat:
    path: '/etc/apt/sources.list.backup'
  register: fileExists
  when: aptRepoName == "sources"
  tags: [rollback, apt-repository, check-defaults]

- name: ROLLBACK APT REPOSITORY | Restore the default apt sources.list file
  copy:
    src: '/etc/apt/sources.list.backup'
    dest: '/etc/apt/sources.list'
    remote_src: true
  register: isRestored
  when: fileExists is defined and fileExists is not skipped
  tags: [rollback, apt-repository, restore-defaults]

- name:
    ROLLBACK APT REPOSITORY | Remove additionnal "{{ aptRepoName }}" repository file from
    /etc/apt/sources.list.d/
  file:
    path: '/etc/apt/sources.list.d/{{ aptRepoName }}.list'
    state: absent
    force: true
  tags: [rollback, apt-repository, remove-repository]
