# ansible_path/roles/users/user/tasks/main.yaml
---
- name: USER | Check if the user exists
  ansible.builtin.getent:
    database: passwd
    key: '{{ userName }}'
  register: userExists
  tags: [users, user, check-user]

# - name: Debug userExists variable
#   ansible.builtin.debug:
#     var: userExists

- name: USER | Create the user {{ userName }}
  ansible.builtin.user:
    name: '{{ userName }}'
    password: '{{ userPassword }}'
    group: '{{ userGroup }}'
    create_home: '{{ userCreateHome }}'
    home: '{{ userHome }}'
    shell: '{{ userShell }}'
    generate_ssh_key: '{{ userSsh }}'
    state: present
  # changed_when: userExists is false
  # when: not userExists
  tags: [users, user, create-user]
