# ansible_path/rollbacks/dockerServices/letsencrypt/tasks/main.yaml
---
- name: ROLLBACK DOCKER SERVICES LETSENCRYPT | Stop the letsencrypt-companion container
  community.docker.docker_container:
    name: '{{ letsencryptContainerName }}'
    state: absent
    container_default_behavior: compatibility
    purge_networks: yes
  tags: [rollback, dockerServices, stopContainer, letsencrypt]

- name: ROLLBACK DOCKER SERVICES LETSENCRYPT | Remove letsencrypt-companion image
  community.docker.docker_image:
    name: '{{ letsencryptImage }}'
    state: absent
    force_absent: yes
  tags: [rollback, dockerServices, removeImage, letsencrypt]
