# ansible_path/rollbacks/dockerServices/mongo/tasks/main.yaml
---
- name: ROLLBACK DOCKER SERVICES MONGO | Stop the mongodb container
  community.docker.docker_container:
    name: '{{ mongoContainerName }}'
    state: absent
    container_default_behavior: compatibility
    purge_networks: yes
  tags: [rollbacks, dockerServices, stopContainer, mongodb]

- name: ROLLBACK DOCKER SERVICES MONGO | Remove mongodb image
  community.docker.docker_image:
    name: '{{ mongoImage }}'
    state: absent
    force_absent: yes
  tags: [rollbacks, dockerServices, removeImage, mongodb]
